### PR TITLE
Allow to change isVideoMirrored option for front camera

### PR DESCRIPTION
**Pull request by luvacu**
Retaking #120 from master

### CODE REVIEW

**Comment by luvacu** [comment]
@jonandersen Could you please review and provide feedback if needed?

**Comment by luvacu** [comment]
@Awalz @jonandersen Any chance this PR gets merged, please? It's quite simple and I think it will benefit others.

**Comment by ThoseGuysInTown** [comment]
In what scenario would you not flip the front camera? (no the project owner, just curious)
Also they haven't responded to mine either & its been quite a while :(

**Comment by luvacu** [comment]
We are **not** flipping the front camera (but the preview layer!), so the exported video looks as if it was recorded with the back camera. For example, if you're holding a sign with letters, it will be readable in the exported video.

**Comment by luvacu** [comment]
Closing. Repo seems abandoned.

**Pull request closed without merging**
