### PR TITLE
Use of CoreMotion instead of UIDevice to detect orientation

### PR DESCRIPTION
**Pull request by jonandersen**
This improves on the previous orientation detection that was implemented using UIDevice, that will only triggered as long as users haven't locked their screen. CoreMotion will always send these updates regardless if the user have locked the screen or not, which would be the desired behavior for most cases. I haven't done to much performance benchmarking but I believe the frequency of CoreMotion updates checks should be ok.

### CODE REVIEW

**Comment by Awalz** [comment]
Thanks for the pull. I will review the changes tonight

**Comment by kharmabum** [comment]
Personally, I've found this implementation to be more useful than the notification based solution on `master` as this implementation will work even if the device orientation is locked.

**Comment by jonandersen** [comment]
@Awalz Is this something you still are interested of using? I personally believe using Core Motion is what users expects and prefers, having to unlock their phone rotation to record in landscape is not very user friendly.

**Comment by Awalz** [comment]
I very much would like to use Core Motion instead of the current implementation. I had hoped to rewrite the current rotation handling by now using your PR. If I could go back in time, I would have merged this. Currently the handling is messy and requires to be gutted and replaced.

**Comment by jonandersen** [comment]
@Awalz Let me know if you need any help with this!  I'm currently using it in my app [1] so will be continuing to use library, but currently using my own fork since I need the core motion support. 

[1] https://itunes.apple.com/app/apple-store/id1021405859?mt=8

**Comment by Awalz** [comment]
Thanks @jonandersen, I would definitely appreciate your help with this! I have added you as a collaborator to the project.

Leap Second looks very cool! I should look into adding a README section for apps currently using SwiftyCam to give visibility to these projects

**Comment by jonandersen** [comment]
@Awalz thanks! I'll submit a new updated PR based of the latest master branch!

**Comment by Awalz** [comment]
Sounds great! You should check out the Swift4 branch I just updated. Theres some API breaking changes in it that will be be made into version 3.0.0 once Swift 4 is released

**Pull request closed without merging**
